# https://github.com/clean-docker/ghost-cms/blob/master/docker-compose.yml
version: "3"
services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    ports:
      - 3030:2368
    environment:
      # url: http://blog.lopesdesign.com
      url: http://localhost:3030/
      server__host: "0.0.0.0"
      server__port: 2368
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      # mail__options__auth__pass: ${MAILGUN_PASSWORD}
    volumes:
      - ./content:/var/lib/ghost/content
      # following is for dev work on the theme, comment in for local dev
      - ../attila-theme.blog.lopesdesign.com/:/var/lib/ghost/content/themes/attila-theme.blog.lopesdesign.com/

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    #  comment out volumes for dev, in fact not using in prod currently
    # volumes:
    #   - /etc/letsencrypt/:/etc/letsencrypt/
    #   - /usr/share/nginx/html:/usr/share/nginx/html
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
